# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac04d95077213ef91545e43896fb2d4728aaad632fa764ca441b8c1288927eb75109b21fcd1bb82405991f71c0a8980ad692de053b81d1a7cf4ca0052984233

test:
  secret_key_base: fbcd44bbc3ab0cd63a8b43350e73a99e168c783a1493244de82820e3135eb654a3d01f9ca52bdefb42a791b40bf5a2f97cc4441f3917e2e8f0584b0628a44b7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
